apiVersion: v1
kind: PersistentVolume
metadata:
   name: vol01
spec:
   capacity:
      storage: 10Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Recycle
   nfs:
      path: /var/nfs/share1
      server: 192.168.27.100
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: vol02
spec:
   capacity:
      storage: 10Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Recycle
   nfs:
      path: /var/nfs/share2
      server: 192.168.27.100
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: vol03
spec:
   capacity:
      storage: 10Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Recycle
   nfs:
      path: /var/nfs/share3
      server: 192.168.27.100
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: vol04
spec:
   capacity:
      storage: 10Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Recycle
   nfs:
      path: /var/nfs/share4
      server: 192.168.27.100
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: vol05
spec:
   capacity:
      storage: 10Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Recycle
   nfs:
      path: /var/nfs/share5
      server: 192.168.27.100
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: vol06
spec:
   capacity:
      storage: 10Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Recycle
   nfs:
      path: /var/nfs/share6
      server: 192.168.27.100
